### PR TITLE
Fix nchook formula to work with brew 4.2

### PR DESCRIPTION
**Pull request by stephenjamieson**

### CODE REVIEW

**Comment by Who23** [comment]
Hello, I appreciate the PR! However this fix doesn't actually work on my system - I've tried to modify it a bit with no luck. I've filed an issue in homebrew-services to try and resolve it, but until then the formula won't work as a service.

**Comment by stephenjamieson** [comment]
Oh interesting, it seems to work for me.  At least the service is running 

```bash
brew services stop nchook
Stopping `nchook`... (might take a while)
==> Successfully stopped `nchook` (label: homebrew.mxcl.nchook)
```

```bash
brew services start nchook
==> Successfully started `nchook` (label: homebrew.mxcl.nchook)
```

```bash
ps auxww| grep nchook
user           64119   0.0  0.1 408894512  19248   ??  S     1:25PM   0:00.08 /opt/homebrew/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python /opt/homebrew/opt/nchook/bin/nchook
```

I must have done something else (in addition) that I don't remember...

**Comment by Who23** [comment]
Weird. Might be something wrong with my homebrew, I'll try to debug it.

**Comment by Who23** [comment]
I did manage to fix the issue, required some small changes but was also due to some mistakes on my part. I've updated the formula in the latest commit.

**Pull request closed without merging**
